# Generated by Django 4.1.7 on 2023-08-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title1',
            field=models.CharField(default=1, max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
